version: '3'
services:
 redis:
  image: redis:alpine
  container_name: rediska
  restart: on-failure
  ports:
   - 6379:6379
  env_file:
   - .env
 postgres:
  image: postgres:latest
  container_name: psqldb
  env_file:
   - .env
  ports:
   - 5432:5432
  restart: on-failure 
 mongo:
  image: mongo:latest
  container_name: logs
  ports:
   - 27017:27017
  env_file:
   - .env
  restart: on-failure 